# mappers.conf - paths to aligners
# Edit these values if your tools are installed elsewhere.
# Provided by user:
export BWA_MEM="/gpfs/ryabykhgrigory/bin" #bwa mem
export STAR="/gpfs/ryabykhgrigory/bin" #STAR
export HISAT2="/gpfs/ryabykhgrigory/bin" #hisat2
export BOWTIE2="/gpfs/ryabykhgrigory/bin" #bowtie2

export WORK_DIR="/gpfs/ryabykhgrigory/mapping_screen_new_branch/mapper_parameters_screen_tool" #working directory


DIR_PATH="/gpfs/ryabykhgrigory/mapping_screen_new_branch/mapper_parameters_screen_tool"
export FASTQ_INPUTS="${DIR_PATH}/SRR18961956_GSM6071448_LW_grid_rep1_DNA_Sus_scrofa_OTHER_999931.dna.rsites.fastq,${DIR_PATH}/SRR18961957_GSM6071449_LW_grid_rep1_RNA_Sus_scrofa_OTHER_999931.rna.rsites.fastq"

# Output prefix for index and results
export OUTPUT_PREFIX="Sus_scrofa.Sscrofa11.1.dna.toplevel"

export CONTACT_SCRIPT="/gpfs/ryabykhgrigory/bin/Bam_to_Contacts_grisha_fix.py"
export EDIT_DISTANCE_CIGAR_FILTER_SCRIPT="/gpfs/ryabykhgrigory/bin/EditDistance_CIGAR_filter.py"

export N_READS_INPUT=999931
