export BWA_MEM="/tools/bwa"
export STAR="/tools/star"
export HISAT2="/tools/hisat2"
export BOWTIE2="/tools/bowtie2"

export WORK_DIR="/output"

export FASTQ_INPUTS="/input/file1.fastq,/input/file2.fastq"

export CONTACT_SCRIPT="/tools/Bam_to_Contacts.py"
export EDIT_DISTANCE_CIGAR_FILTER_SCRIPT="/tools/EditDistance_CIGAR_filter.py"
